export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";
export const CREATE_PATIENT_ERROR = "CREATE_PATIENT_ERROR";

export const LIST_PATIENT_SUCCESS = "LIST_PATIENT_SUCCESS";
export const LIST_PATIENT_ERROR = "LIST_PATIENT_ERROR";

export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_ERROR = "UPDATE_PATIENT_ERROR";

export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const DELETE_PATIENT_ERROR = "DELETE_PATIENT_ERROR";

export const RESET_INITIAL_STATE = "RESET_INITIAL_STATE";