export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS" ;
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";